--- 
- name: "create EA4 default profile config"
  template: 
    dest: /tmp/ea4_profile.json
    group: root
    mode: 0644
    owner: root
    src: ea4_profile.json.j2

- name: "Install EA4"
  shell: " /scripts/migrate_ea3_to_ea4 --run --yes --force --skip-blockers --install_profile /tmp/ea4_profile.json"
  register: ea4_enabled

- name: "Optimize EA4"
  template:
    dest: /var/cpanel/conf/apache/local
    group: root
    mode: 0644
    owner: root
    src: apache_local.j2

- name: "copy php.ini to multiPHP ver"
  template: 
    dest: "/opt/cpanel/ea-php{{ item }}/root/etc/php.ini"
    group: root
    mode: 420
    owner: root
    src: php.ini.j2
  with_items: 
    - 54
    - 55
    - 56
    - 70
    - 71

- name: "Resolv.conf"
  template:
    dest: /etc/resolv.conf
    group: root
    mode: 0644
    owner: root
    src: resolv.conf.j2

- name: "Named opti"
  template:
    dest: "/etc/named.conf"
    group: named
    mode: 0644
    owner: named
    src: named.conf

- name: "rebuild httpd config"
  command: /scripts/rebuildhttpdconf 

- name: "rebuild dns config"
  command: /scripts/rebuilddnsconfig


- name: "FTP opti"
  template:
    dest: /var/cpanel/conf/pureftpd/main
    group: root
    mode: 0644
    owner: root
    src: ftp.conf.j2

- name: "MYSQL Cnf"
  template:
    dest: /etc/my.cnf
    group: root
    mode: 0644
    owner: root
    src: my.cnf
