---
- lineinfile:
    dest: /etc/ssh/sshd_config
    insertafter: '^#Port '
    line: 'Port 1243'

- lineinfile:
    dest: /etc/ssh/sshd_config
    insertafter: '^#PermitRootLogin'
    line: 'PermitRootLogin no'

- copy: content="{{ wheel_password }}" dest=/root/.admin_pass

- user:
    name=admin
    group=wheel
    update_password=always
    state=present
    password={{ wheel_password |password_hash('sha512') }} 

